pub const CURRENT: DimensionVector = DimensionVector([0, 0, 0, 1, 0, 0, 0, 0]);
pub const TEMPERATURE: DimensionVector = DimensionVector([0, 0, 0, 0, 1, 0, 0, 0]);
pub const SUBSTANCE: DimensionVector = DimensionVector([0, 0, 0, 0, 0, 1, 0, 0]);
pub const LUMINOUS: DimensionVector = DimensionVector([0, 0, 0, 0, 0, 0, 1, 0]);
pub const VELOCITY: DimensionVector = DimensionVector([1, -1, 0, 0, 0, 0, 0, 0]);
pub const FORCE: DimensionVector = DimensionVector([1, -2, 1, 0, 0, 0, 0, 0]);
pub const ENERGY: DimensionVector = DimensionVector([2, -2, 1, 0, 0, 0, 0, 0]);
pub const POWER: DimensionVector = DimensionVector([2, -3, 1, 0, 0, 0, 0, 0]);
pub const TORQUE: DimensionVector = DimensionVector( [2, -2, 1, 0, 0, 0, 0, 1]);